### PR TITLE
Add "AppDir.runtime.preserve"

### LINKED ISSUE #189: [Feature Request] Allow Excluding File From `PT_INTERP` Change (Or Add `AppDir.files.do_not_modify`)
(This change is extremely niche, but shouldn't be too hard to implement.)

I'm making a predominately x86_64 AppImage that contains an ARM binary.

Normally, my program depends on `libc6-armhf-cross:all` which installs a binary interpreter at `/usr/arm-linux-gnueabihf/lib/ld-linux-armhf.so.3`. Then I can use QEMU user-mode's `QEMU_LD_PREFIX` environmental variable to make `/lib/ld-linux-armhf.so.3` resolve correctly to it. And it works great!

This allows me to install and run an ARM binary without actually installing `/lib/ld-linux-armhf.so.3` at the correct place. Which is necessary because installing it there requires an ARM package from an ARM repo. And that is bad because Ubuntu's multi-arch support with ARM is terrible, like it requires you to add the Ubuntu Ports repo manually, then block ARM from all other repos to prevent `apt update` from failing. Bottom-line: it is extremely beneficial to just use `libc6-armhf-cross:all` at `/usr/arm-linux-gnueabihf/lib/ld-linux-armhf.so.3`.

The behavior of replacing `PT_INTERP` breaks this for 2 reasons:
1. It fully replaces `PT_INTERP`, meaning I can't just slap on a `$APPDIR/usr/arm-linux-gnueabihf/` prefix and have it resolve. Instead it would resolve to `$APPDIR/usr/arm-linux-gnueabihf/tmp/appimage-8t2fP7a-ld-linux-armhf.so.3` which doesn't exist.
2. It tries to mount `/lib/ld-linux-armhf.so.3` from the host system, which for reasons mentioned above doesn't exist. This is justa warning though.

The relevant code: https://github.com/AppImageCrafters/appimage-builder/blob/f10b7d19181d8dbf911ee9bc08dc0c188d7f6601/appimagebuilder/modules/setup/helpers/libc.py#L93

My suggestion would be to add a `do_not_modify` list to `AppDir.files`, and all files listed would remain intact.

Thank you!

### PR DESCRIPTION
**Pull request by TheBrokenRail**
Fixes #189

Example:
```yml
AppDir:
    runtime:
        preserve:
            - usr/bin/example
```

It only changes the behavior of `appimagebuilder/modules/setup/helpers/libc.py`, but as far as I can tell, that's the only file that actually modifies files rather than just moving them around (correct me if I'm wrong).

Currently, it also doesn't stop files from being moved for instance to `/opt/libc`.

### CODE REVIEW

**Comment by TheBrokenRail** [comment]
Any update in this?

**Comment by azubieta** [comment]
Sorry haven't had chance to look at this. Please use the `black` formatter.
Will add more comments later.

**Comment by TheBrokenRail** [comment]
Done!

**Comment by azubieta** [comment]
I will rework your PR to make it work over the v1.0.0 code. I should be ready for v1.0.1 ;)

**Comment by TheBrokenRail** [comment]
I fixed all the merge conflicts!

**Comment by azubieta** [comment]
Merged! Thanks a lot for the help!

**Pull request merged**
