### PR TITLE
Replaces packaging with pydpkg for comparing dpkg package versions

### PR DESCRIPTION
**Pull request by serghov**
appimage-builder uses packaging to compare dpkg package versions, however versions such as `1.19.7ubuntu3` which do not conform with PEP 440 are not supported by packaging library. 
This pull request replaces packaging with pydpkg which supports those cases for apt.

Relevant issue #280 

~~I have done some limited testing, however it would be better to have a unit tests for these cases which this pull request does not include since I am not sufficiently familiar with the codebase.~~

I have also added a simple unit test for testing apt package version comparison.

### CODE REVIEW

**Comment by iTrooz** [comment]
Not working here, because the dependency 'python-dpkg' is not found. Isn't it 'pydpkg' ?
Also, I think you need to add it to setup.py

**Comment by serghov** [comment]
@iTrooz I am not quite sure, you're right about pydpkg, but I am not sure if it needs to be in Pipfile or setup.py. I can get it to build and work with Pipfile.

**Comment by iTrooz** [comment]
I got this error with your current branch, I assume it is because it doesn't even try to install pydpkg
https://github.com/iTrooz/ImHex/actions/runs/3722257274/jobs/6312938623

If I understand the Pipfile well, it's only useful for dev environments

**Comment by iTrooz** [comment]
Just got a successful build with this branch : https://github.com/iTrooz/appimage-builder/tree/dpkg-package-versions
https://github.com/iTrooz/ImHex/actions/runs/3724906010/jobs/6317376889

**Comment by serghov** [comment]
@iTrooz I have added your commit to the pull request.

**Review by azubieta — APPROVED** [review]
This looks good to me, many thanks!

**Comment by pbek** [comment]
Any chance getting this PR into a release. 😉

**Pull request merged**
